language: node_js

node_js:
  - "node"

dist: trusty

addons:
  sonarcloud:
    organization: "m4rk9696-github"
    token: $SONAR_TOKEN

script:
  - yarn build
  - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.sonar/cache'

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: home-blocks.zip
  skip_cleanup: true
  on:
    tags: true
